---
version: "3.4"

services:
  db:
    image: postgres:${POSTGRES_TAG}
    container_name: igcp_db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
  mlflow:
    depends_on:
      - db
    build: ./mlflow
    container_name: igcp_mlflow
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - MLFLOW_ARTIFACT_ROOT
      - MLFLOW_HOST
      - MLFLOW_PORT
    ports:
      - ${MLFLOW_PORT}:5000
    volumes:
      - mlflow_data:${MLFLOW_ARTIFACT_ROOT}
    restart: unless-stopped
  waitformlflow:
    depends_on:
      - mlflow
    image: dadarek/wait-for-dependencies:${WAIT_TAG}
    container_name: igcp_waitformlflow
    command: mlflow:5000
  training:
    depends_on:
      - waitformlflow
    build: ./training
    container_name: igcp_training
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

volumes:
  db_data:
    name: igcp_db_data
  mlflow_data:
    name: igcp_mlflow_data
